### ISSUE TITLE
Strange installation method?

### ISSUE THREAD

**Issue by JustinAzoff** [salesforce/GQUIC_Protocol_Analyzer#1]
Hi!

I'm wonder why  the README says to re-run init-plugin and  copy files over.. Were you having some sort of problem that this was fixing.  I'm able to build it just fine using the usual:

```
source  ~/src/bro-2.6/build/bro-path-dev.sh
./configure --bro-dist=$HOME/src/bro-2.6
make
```

and with master installed in /usr/local it builds and runs with a normal ./configure && make

**Comment by Cable-2-5** [comment]
Hi,

There weren't any issues when building it as is, but I found that using init-plugin was a straightforward way to generate some files if you did not want to copy over everything.
